### ISSUE TITLE
Flaky Test in org.datadog.jmeter.plugins.DatadogBackendClientTest.testExtractLogs

### ISSUE THREAD

**Issue by tt0suzy** [DataDog/jmeter-datadog-backend-listener#32]
**Describe the bug**
`org.datadog.jmeter.plugins.DatadogBackendClientTest.testExtractLogs`
Is a flaky test. It can pass mvn test but when run using the tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), it fails. NonDex is a tool that will introduce non-determinism in certain java collections. It matters to fix this flaky test as it may cause potential issues due to the uncertainty of orders from converting JSON objects to string rather than the program itself. The test shows below:
```
-------------------------------------------------------------------------------
Test set: org.datadog.jmeter.plugins.DatadogBackendClientTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.547 s <<< FAILURE! - in org.datadog.jmeter.plugins.DatadogBackendClientTest
testExtractLogs(org.datadog.jmeter.plugins.DatadogBackendClientTest)  Time elapsed: 1.492 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[body_size":0.0,"sent_bytes":124.0,"sample_start_time":1.0,"data_encoding":null,"sample_end_time":126.0,"error_count":0.0,"load_time":125.0,"response_code":"123","idle_time":0.0,"headers_size":0.0,"thread_name":"bar baz","all_threads":0.0,"ddsource":"jmeter","sample_label":"foo","sample_count":10.0,"bytes":12345.0,"message":"","thread_group":"bar","url":"","group_threads":0.0,"content_type":"","connect_time":0.0,"data_type":"","latency":12.0]}> but was:<{"[sample_start_time":1.0,"response_code":"123","headers_size":0.0,"sample_label":"foo","latency":12.0,"group_threads":0.0,"idle_time":0.0,"error_count":0.0,"message":"","url":"","ddsource":"jmeter","sent_bytes":124.0,"thread_group":"bar","body_size":0.0,"content_type":"","load_time":125.0,"thread_name":"bar baz","sample_end_time":126.0,"bytes":12345.0,"connect_time":0.0,"sample_count":10.0,"data_type":"","all_threads":0.0,"data_encoding":null]}>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.datadog.jmeter.plugins.DatadogBackendClientTest.testExtractLogs(DatadogBackendClientTest.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
**To Reproduce**
1. Build the module
     `mvn install -pl . -am -DskipTests`
2. Run the test using NonDex 
    ` mvn -pl . edu.illinois:nondex-maven-plugin:2.1:nondex -am -Dtest=org.datadog.jmeter.plugins.DatadogBackendClientTest#testExtractLogs`
3. The result will be saved under the module folder in .nondex

**Expected behavior**
The test should be passed.
```
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] Test results can be found at: 
[INFO] file:///home/yichen28/jmeter-datadog-backend-listener/.nondex/v9QRBH5WZ52sb+s1cqqrTlC3Dt2VvpoPR0HEPh5gA=/test_results.html
[INFO] [NonDex] The id of this run is: v9QRBH5WZ52sb+s1cqqrTlC3Dt2VvpoPR0HEPh5gA=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.313 s
[INFO] Finished at: 2022-11-24T20:36:09-06:00
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.5 LTS

**Additional context**

**Comment by FlorentClarret** [comment]
I merged the PR. Closing this issue, thanks!
